version: 2.1

jobs:
  Build-and-Test-Backend:
    executor:
      name: go/default
      tag: '1.14'
    steps:
      - checkout
      - go/load-cache
      - go/mod-download-cached
      - run:
          name: go build
          command: go build ./...
      - go/test:
          failfast: true

workflows:
  version: 2
  Backend-Workflow:
    jobs:
      - Build-and-Test-Backend

orbs:
  go: circleci/go@1.3.0