version: 2.1

jobs:
  Build-Backend:
    executor:
      name: go/default
      tag: '1.14'
    steps:
      - checkout
      - go/load-cache
      - run:
          name: go build
          command: go build ./...

  Test-Backend:
    docker:
      - image: circleci/golang:1.14

    environment: # environment variables for the build itself
      TEST_RESULTS: /tmp/test-results # path to where test results will be saved

    steps:
      - run: mkdir -p $TEST_RESULTS
      - run: go get github.com/jstemmer/go-junit-report
      - run:
          name: Run unit tests
          command: go test -v ./... 2>&1 | go-junit-report > ${TEST_RESULTS}/go-test-report.xml
      - go/save-cache
      - store_test_results:
          path: /tmp/test-results

workflows:
  version: 2
  Backend-Workflow:
    jobs:
      - Build-Backend
      - Test-Backend:
          requires:
            - Build-Backend

orbs:
  go: circleci/go@1.3.0