version: 2.1

jobs:
  Build-and-Test-Backend:
    executor:
      name: go/default
      tag: "1.14"
    steps:
      - checkout
      - go/mod-download-cached
      - run:
          name: go build
          command: go build ./...
      - go/test:
          failfast: true
  Build-Frontend:
    executor:
      name: node/default
      app-dir: ~/project/frontend
      tag: '15'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn run build
          name: yarn build

workflows:
  version: 2
  Backend-Workflow:
    jobs:
      - Build-and-Test-Backend
  Frontend-Workflow:
    jobs:
      - Build-Frontend

orbs:
  go: circleci/go@1.3.0
  node: circleci/node@4.2.0
