name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install deps
        run: yarn install
        working-directory: ./frontend
      - name: Run prettier
        run: yarn lint
        working-directory: ./frontend
      - name: build
        run: yarn build
        working-directory: ./frontend
